import { ClerkProvider } from '@clerk/nextjs'
import Head from 'next/head';
import { rubik } from './ui';
import './globals.css';

export const metadata = {
  title: 'PersonalCloud',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="es">
        <Head>
          <link rel="shortcut icon" href="/favicon.ico" />
        </Head>
        <body className={`${rubik.className} antialiased page`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
